export const surpriseMePrompts = [
    'Batman and Robin trying to stop the Joker from turning Gotham City into a giant amusement park',
    'Spider-Man and Deadpool teaming up to stop a bank robbery, but they keep cracking jokes and getting distracted',
    'The Avengers having a potluck dinner, but Thors Asgardian dishes are too exotic for the others',
    'The X-Men playing a game of mutant baseball, with their powers causing chaos on the field',
    'Superman and Wonder Woman on a romantic date, but they keep getting interrupted by supervillain attacks',
    'The Teenage Mutant Ninja Turtles trying to teach Master Splinter how to use the internet',
    'The Fantastic Four accidentally swapping powers and having to deal with the consequences',
    'Archie and the gang from Riverdale getting caught up in a time-travel adventure',
    'The Justice League playing a game of truth or dare, with hilarious and embarrassing results',
    'The Powerpuff Girls trying to stop a giant monster made entirely of candy',
    'The Incredibles family going on a normal family vacation, but their superhero antics keep ruining it',
    'Batman and Catwoman teaming up to stop the Penguin from stealing a priceless diamond, but they cant stop flirting with each other',
    'The Guardians of the Galaxy getting lost in space and having to rely on a talking tree for directions',
    'The Simpsons family accidentally stumbling upon a secret superhero society in Springfield',
    'Iron Man and Captain America having a rap battle to settle their differences',
    'The Hulk trying to learn meditation and yoga to control his anger, but its not going well',
    'Deadpool breaking the fourth wall and interacting with the comic book artist drawing him',
    'The Scooby-Doo gang investigating a haunted comic book convention',
    'The Tick and Arthur trying to stop a supervillain who can control the weather',
    'The Watchmen reuniting to stop a new threat, but theyre all much older and out of shape',
    'The Punisher and Daredevil teaming up to take down a corrupt politician, but they have very different methods',
    'The Hellboy crew investigating a haunted circus thats come to town',
    'The X-Men trying to teach a new mutant how to control their powers, but its not going well',
    'The Teenage Mutant Ninja Turtles getting lost in the sewers and ending up in a different city',
    'The Justice League playing a game of superhero charades, but they keep using their powers to cheat',
]